# Generated by Django 2.1.7 on 2019-04-02 16:12

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190402_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=240, validators=[accounts.validators.validate_author_email]),
        ),
    ]
