# Generated by Django 2.1.7 on 2019-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190402_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(error_messages={'blank': "this can't be null", 'unique': 'This Number is not unique, please try again'}, max_length=10, unique=True),
        ),
    ]
