# Generated by Django 2.1.7 on 2019-04-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190403_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('drinks', 'Drinks'), ('fastfood', 'Fastfood'), ('deserts', 'Deserts')], default='drinks', max_length=100)),
                ('Item', models.CharField(max_length=200)),
                ('Price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='mobile',
            field=models.IntegerField(error_messages={'blank': "this can't be null", 'unique': 'This Number is not unique, please try again'}, max_length=10, unique=True),
        ),
    ]
