# Generated by Django 2.1.7 on 2019-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190403_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='mobile',
            field=models.IntegerField(error_messages={'blank': "this can't be null", 'unique': 'This Number is not unique, please try again'}, unique=True),
        ),
    ]
