# Generated by Django 2.1.7 on 2019-04-03 20:02

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_auto_20190403_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=240, validators=[accounts.validators.validate_author_email])),
                ('username', models.CharField(error_messages={'blank': "this can't be null", 'unique': 'This Username is not unique, please try again'}, max_length=200, unique=True)),
                ('mobile', models.IntegerField(error_messages={'blank': "this can't be null", 'unique': 'This Number is not unique, please try again'}, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
