# Generated by Django 2.1.7 on 2019-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quntity', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
            ],
        ),
    ]
