# Generated by Django 2.1.7 on 2019-04-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Quntity',
            new_name='Quantity',
        ),
    ]
