# Generated by Django 2.1.7 on 2019-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190404_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderedmeal',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
