# Generated by Django 2.1.7 on 2019-04-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190405_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmeal',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
