# Generated by Django 2.1.7 on 2019-04-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_orderedmeal_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedmeal',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
    ]
