# Generated by Django 2.1.7 on 2019-04-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190409_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedmeal',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
