# Generated by Django 2.1.7 on 2019-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190409_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedmeal',
            name='menu',
        ),
        migrations.AddField(
            model_name='orderedmeal',
            name='menu',
            field=models.ManyToManyField(related_name='ordered_meals', to='accounts.Menu'),
        ),
    ]
