# Generated by Django 2.1.7 on 2019-04-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190410_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Item_Price',
            new_name='Price',
        ),
    ]
