# Generated by Django 2.1.7 on 2019-04-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190412_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedmeal',
            name='meal_items',
        ),
        migrations.AddField(
            model_name='orderedmeal',
            name='meal_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='accounts.MealItem'),
            preserve_default=False,
        ),
    ]
