# Generated by Django 2.1.7 on 2019-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20190412_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='menu',
            field=models.ManyToManyField(to='accounts.Menu'),
        ),
    ]
