# Generated by Django 2.1.7 on 2019-04-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20190412_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedmeal',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
