# Generated by Django 2.1.7 on 2019-04-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20190412_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedmeal',
            name='meal_items',
        ),
        migrations.DeleteModel(
            name='OrderedMeal',
        ),
    ]
